/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pansyqq_crypter_Java2CJNI */

#ifndef _Included_com_pansy_robot_crypter_JNI_ECDH
#define _Included_com_pansy_robot_crypter_JNI_ECDH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pansyqq_crypter_Java2CJNI
 * Method:    ecdh
 * Signature: ()Lcom/example/pansyqq/crypter/ECC;
 */
JNIEXPORT jobject JNICALL Java_com_pansy_robot_crypter_JNI_1ECDH_ecdh
  (JNIEnv *, jobject,jobject)__attribute__((section(".encryptFun")));

  JNIEXPORT jbyteArray JNICALL Java_com_pansy_robot_crypter_JNI_1ECDH_ecdh2
    (JNIEnv *, jobject,jobject,jbyteArray);

/*
 * Class:     com_example_pansyqq_crypter_Java2CJNI
 * Method:    ecdh2
 * Signature: (Lcom/example/pansyqq/crypter/ECC;[B)[B
 */


#ifdef __cplusplus
}
#endif
#endif
